version: '3'
services:
  backend-test:
    image: pwndoc-ng/pwndoc-ng:backend-test
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: pwndoc-ng-backend-test
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./jest.config.js:/app/jest.config.js
    environment:
      API_URL: https://localhost:4242
    network_mode: host
